### ISSUE TITLE
macos:systemsetup_state missing entities

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#100]
**Describe the bug**
The systemsetup_item has entities for restartpowerfailure and localsubnetname, but they are missing from the systemsetup_state.  We should fix this by adding corresponding state entities.

**OVAL details** (complete all those relevant)
 - Schema: macos-definitions-schema.xsd

**Comment by wmunyan** [comment]
Indeed they are missing from the `systemsetup_state`.  No objections to this fix.

**Comment by solind** [comment]
https://github.com/OVAL-Community/OVAL/commit/a5ae8d71b311f35cb7f25c5a09dc3bdfdf875a9b
