### ISSUE TITLE
Need a mechanism to query macOS for positively disabled services

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#101]
**Abstract**
There is currently no way to query macOS to identify launchctl services that have been intentionally disabled, i.e., the output from ```launchctl print_disabled system```.  I propose we create a new macos:disabledservice_test.

**Link to Proposal**
PR to come.

**Additional context**
See attached sample content.

[content.zip](https://github.com/OVAL-Community/OVAL/files/4796015/content.zip)

**Comment by wmunyan** [comment]
Clarifying question:  The output of the command shows the name of the service, and then a ` => true/false` value.  Does `true` mean the service is disabled?  Then `false` means the service is not disabled?  If the service is not disabled, why is it in the "print-disabled" output?

I don't have objection to adding this test, just clarification on what the output means, I guess.

**Comment by solind** [comment]
I believe "true" means the corresponding service is disabled.  It's a little confusing!

**Comment by solind** [comment]
https://github.com/OVAL-Community/OVAL/commit/a5ae8d71b311f35cb7f25c5a09dc3bdfdf875a9b
