### ISSUE TITLE
Deprecate macos:diskutil_test

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#102]
**Abstract**
The diskutil_test was originally created to leverage MacOSX utilities that could identify corruptions in installed packages, somewhat similar to how RPM verify works.  However, this functionality was deprecated in El Capitan (10.11) and eliminated entirely in Sierra (10.12).  So, we might as well deprecate this test now -- it is not relevant to any currently-supported version of OSX.

**Link to Proposal**
PR to come.

**Comment by wmunyan** [comment]
No objections.

**Comment by solind** [comment]
https://github.com/OVAL-Community/OVAL/commit/a5ae8d71b311f35cb7f25c5a09dc3bdfdf875a9b
