### ISSUE TITLE
macos:nvram_test enhancements

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#103]
**Abstract**
I have recently discovered that there is at least one important nvram property key that is not included in the scope of properties enumerated by the ```nvram -p``` command.  Therefore, we need to clarify the documentation on this test, to indicate that we will use only nvram -p expressed properties when operations other than "equals" are indicated in the object, but that the interpreter should attempt to retrieve any other specified key if the "equals" operator is indicated.

Additionally, I have discovered that nvram values are stored primitively as binary (NSData) plist data.  Therefore we should probably really be using an Entity[State/Item]BinaryType instead of the String type to store this data.  This would require a new nvram512_test/object/state.

**Link to Proposal**
PR to come.

**Additional context**
See attached sample content for the new nvram512 binary test.

[content.zip](https://github.com/OVAL-Community/OVAL/files/4796043/content.zip)

**Comment by wmunyan** [comment]
No objections to this one.

**Comment by solind** [comment]
https://github.com/OVAL-Community/OVAL/commit/a5ae8d71b311f35cb7f25c5a09dc3bdfdf875a9b
