### ISSUE TITLE
Need a test to query FileVault status on macOS

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#105]
**Abstract**
On macOS, disk encryption has passed from "core storage" to "FileVault", but we currently have no way to query for FileVault status.  This calls for a new macos:filevault_test.

**Link to Proposal**
PR to come.

**Additional context**
See attachment for sample content.

[content.zip](https://github.com/OVAL-Community/OVAL/files/4796058/content.zip)

**Comment by solind** [comment]
Well maybe it's not fair to say it's "passed", because I think FileVault is built on top of CoreStorage. But it's hard to get a straight answer. At any rate, we need a way to determine the output from the ```fdesetup status``` command -- whether it's enabled, disabled or in the throes of encrypting (i.e., becoming enabled).

**Comment by wmunyan** [comment]
No objections

**Comment by solind** [comment]
https://github.com/OVAL-Community/OVAL/commit/a5ae8d71b311f35cb7f25c5a09dc3bdfdf875a9b
