### ISSUE TITLE
Need a test to check whether a firmware password is enabled on macOS

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#106]
**Abstract**
The command ```firmwarepasswd -check``` can tell you on macOS whether a password has been created for the firmware, but there is no way in OVAL to assess this security-relevant configuration information.  We should add a firmwarepassword_test.

**Link to Proposal**
PR to come.

**Additional context**
See the attached file for sample content.

[content.zip](https://github.com/OVAL-Community/OVAL/files/4796080/content.zip)

**Comment by wmunyan** [comment]
No objections

**Comment by solind** [comment]
https://github.com/OVAL-Community/OVAL/commit/a5ae8d71b311f35cb7f25c5a09dc3bdfdf875a9b
