### ISSUE TITLE
Need a mechanism to check macOS device configuration profile information

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#107]
**Abstract**
There is currently no reliable mechanism to query the MDM enrollment or DEP enrollment status of a macOS device using OVAL.  A new test is needed to access this information using the profiles command.

**Link to Proposal**
PR to come referencing this issue.

**Comment by wmunyan** [comment]
No objections

**Comment by wmunyan** [comment]
Some sample results from CIS-CAT implementation of this test:

[profiles_test_sample_results_CIS-CAT.zip](https://github.com/OVAL-Community/OVAL/files/6165751/profiles_test_sample_results_CIS-CAT.zip)

**Comment by solind** [comment]
Looks good to me!

**Comment by wmunyan** [comment]
PRs have been merged; resolving this issue
