### ISSUE TITLE
Add securitystanza, deviceattribute, inittab, useraccount, and nfso tests to AIX schema

### ISSUE THREAD

**Issue by wmunyan** [OVAL-Community/OVAL#127]
**Abstract**
A number of recommendations in CIS benchmarks deal with the collection and evaluation of AIX security parameters. This proposal adds the lssec_(test|object|state|item) constructs, allowing for the collection and evaluation of these parameter values.

**Link to Proposal**
https://github.com/OVAL-Community/OVAL/pull/126

**Additional context**
N/A

**Comment by wmunyan** [comment]
UPDATES:

- Renamed the `lssec_test` to `securitystanza_test` so as to not name the test after the command being executed and hopefully help be more descriptive.
- Added new tests to aid in implementation (pretty much in line with what would be needed to implement CIS AIX benchmark):
    - `deviceattribute_test`: Displays attribute characteristics and possible values of attributes for devices in the system
    - `inittab_test`: Lists records in the /etc/inittab file.
    - `useraccount_test`: Displays user account attributes
    - `nfso_test`: Manages Network File System (NFS) tuning parameters

**Comment by wmunyan** [comment]
[aix-proposal-test-content.zip](https://github.com/OVAL-Community/OVAL/files/6718422/aix-proposal-test-content.zip)

**Comment by vanderpol** [comment]
Related PR has bee merged to develop, closing issue
