### ISSUE TITLE
Wrong link reference for Unix Definition Schema

### ISSUE THREAD

**Issue by marcusburghardt** [OVAL-Community/OVAL#129]
**Describe the bug**
Some links present at Unix Definitions Schema has a wrong reference which may confuse readers.

I observed that tests which share the same name on both Unix Definition Schema and Windows Definition Schema pages are correctly referenced on Windows Definition Schema page[1] but wrongly referenced on Unix Definition Schema page[2]:

1. https://oval-community-guidelines.readthedocs.io/en/latest/oval-schema-documentation/windows-definitions-schema.html
2. https://oval-community-guidelines.readthedocs.io/en/latest/oval-schema-documentation/unix-definitions-schema.html

The following links are wrongly referenced at Unix Definition Schema page:

- dnscache_test
- file_test
- interface_test
- process_test
- process58_test

However, checking the source file at the repository, the references looks correct:
- https://github.com/OVAL-Community/OVAL/blob/master/guidelines/oval-schema-documentation/unix-definitions-schema.rst

**Replication Steps**
1. Go to https://oval-community-guidelines.readthedocs.io/en/latest/oval-schema-documentation/unix-definitions-schema.html
2. Click on any of the mentioned links above
3. Note they will redirect you for the **"windows-definitions-schema.html"** instead of stay at 'unix-definitions-schema.html' page.

**Expected behavior**
All links for Unix tests should reference a Unix test and not a Windows test.

**Comment by vanderpol** [comment]
@DeafBDoor and/or @A-Biggs, by no means a critical issue, but if you happen to figure out this issue as part of the release/build process that would be great.  It has to do with the same test name in UNIX and Windows schema's, but I have no idea why it's causing issues with our generated docs.

**Comment by DeafBDoor** [comment]
During the build process, there are lots of warnings, including
`/github/workspace/guidelines/oval-schema-documentation/windows-definitions-schema.rst:941: WARNING: duplicate label dnscache_test, other instance in /github/workspace/guidelines/oval-schema-documentation/unix-definitions-schema.rst`

which looks related to this issue.

Adding the entire build output to make it easier to investigate.
[build_warning.txt](https://github.com/user-attachments/files/17837434/build_warning.txt)

**Comment by vanderpol** [comment]
This is partially fixed, it is resolved in the static files that we now bundle with OVAL releases, but still exists as an issue in readthedocs.

**Comment by vanderpol** [comment]
Manual fix in place going forward, calling this closed.
