### ISSUE TITLE
Add Support for IPv4 and IPv6, both, to interfacesType

### ISSUE THREAD

**Issue by johnulmer-oval** [OVAL-Community/OVAL#134]
**Describe the bug**
Currently, the interfacesType in the oval-system-characteristics-schema schema allows only one IP address.  As IPv6 addresses come into common use, that schema needs updating.  Suggest that the schema should allow more than one ip_address element and add an attribute to that element for 'ip_address_version'.

**Replication Steps** (if applicable)
Use any SCAP processor to create OVAL results.  

**Expected behavior**
For network interfaces that have more than one IP address configured, allow the reporting of both IPv4 and IPv6 addresses.

Technically, while not common, it is possible to configure a single interface to have more than one address of each type.  I don't see this often and am open to the idea that updating of the referenced schema might be more robust if it allowed multiple addresses of any type.  However, in common use, currently, it appears that it is typical to have only one IPv4 and only one IPv6 for a given interface.

**Comment by vanderpol** [comment]
I second this item, primarily to ensure it's not auto-closed.
