### ISSUE TITLE
Add function to merge collected item attributes into a single variable with optional delimiter and sorting

### ISSUE THREAD

**Issue by vanderpol** [OVAL-Community/OVAL#135]
**Abstract**
This is primarily a bugfix for dealing with complex data, or order specific data in windows registry multi-sz.  OVAL currently creates separate 'value's for each line in the mult-sz, this makes any order specific or multi-line checks impossible.  We have attempted to use the OVAL concat function, but it does not function this method.   This issue may exists in other probes as well, which is why I'm proposing this be a oval function vs an update to just the Windows registry definition.

**Link to Proposal**
This proposal is fairly simple, and doesn't need some complex document.  Convert a list of strings into a single string
"abc"
"def"
"ghi"

to 
"abcdefghi"

        <local_variable id="oval:test:var:1" version="1" datatype="string" comment="flattened string version of registry values">
          <convert_to_string>
            <object_component object_ref="oval:test:obj:1" item_field="value"/>\
          </convert_to_string>
        </local_variable>

**Additional context**
Here's an example of a registry key multi-size that is known to cause issues:

Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox
  Name:            Preferences
  Type:            REG_MULTI_SZ
  Data:            {
                     "browsser.serach.update":{
                      "value":false,
                      "Status":"locked"
                      },
                     "security.default_personal_cert": {
                       "Value": "Ask Every Time",
                       "Status": "locked"
                     },
                     "browser.search.update": {
                       "Value": false,
                       "Status": "locked"
                     },
                     "dom.disable_window_move_resize": {
                       "Value": true,
                       "Status": "locked"
                     },
                     "dom.disable_window_flip": {
                       "Value": true,
                       "Status": "locked"
                     },
                      "browser.contentblocking.category": {
                       "Value": "strict",
                       "Status": "locked"
                     },
                     "extensions.htmlaboutaddons.recommendations.enabled": {
                       "Value": false,
                       "Status": "locked"
                     }
                   }

When processed by OVAL it creates: the following

<win-sc:hive>HKEY_LOCAL_MACHINE</win-sc:hive>
  <win-sc:key>SOFTWARE\Policies\Mozilla\Firefox</win-sc:key>
  <win-sc:name>Preferences</win-sc:name>
  <win-sc:last_write_time datatype="int">133276820590000000</win-sc:last_write_time>
  <win-sc:type>reg_multi_sz</win-sc:type>
  <win-sc:value>{</win-sc:value>
  <win-sc:value>"security.default_personal_cert": {</win-sc:value>
  <win-sc:value>"Value": "Ask Every Time",</win-sc:value>
  <win-sc:value>"Status": "locked"</win-sc:value>
  <win-sc:value>},</win-sc:value>
  <win-sc:value>"browser.search.update": {</win-sc:value>
  <win-sc:value>"Value": false,</win-sc:value>
  <win-sc:value>"Status": "locked"</win-sc:value>
  <win-sc:value>},</win-sc:value>
  <win-sc:value>"dom.disable_window_move_resize": {</win-sc:value>
  <win-sc:value>"Value": true,</win-sc:value>
  <win-sc:value>"Status": "locked"</win-sc:value>
  <win-sc:value>},</win-sc:value>
  <win-sc:value>"dom.disable_window_flip": {</win-sc:value>
  <win-sc:value>"Value": true,</win-sc:value>
  <win-sc:value>"Status": "locked"</win-sc:value>
  <win-sc:value>},</win-sc:value>
  <win-sc:value>"browser.contentblocking.category": {</win-sc:value>
  <win-sc:value>"Value": "strict",</win-sc:value>
  <win-sc:value>"Status": "locked"</win-sc:value>
  <win-sc:value>},</win-sc:value>
  <win-sc:value>"extensions.htmlaboutaddons.recommendations.enabled": {</win-sc:value>
  <win-sc:value>"Value": false,</win-sc:value>
  <win-sc:value>"Status": "locked"</win-sc:value>
  <win-sc:value>}</win-sc:value>
  <win-sc:value>}</win-sc:value>
  <win-sc:windows_view>64_bit</win-sc:windows_view>

This proposal would concat all of the 'values' into a single string such as:
{"browsser.serach.update":{"value":false,"Status":"locked"},"security.default_personal_cert": {"Value": "Ask Every Time","Status": "locked"},browser.search.update": {"Value": false,"Status": "locked"},"dom.disable_window_move_resize": {"Value": true,"Status": "locked"},"dom.disable_window_flip": {"Value": true,"Status": locked"},"browser.contentblocking.category": {"Value": "strict","Status": "locked"},"extensions.htmlaboutaddons.recommendations.enabled": {"Value": false,"Status": "locked"}}

This would then allow for checking values such as:
browser.search.update": {"Value": false,"Status": "locked"},

There are other windows examples with order specific requirements that this would resolve as well.

**Comment by solind** [comment]
Hi @vanderpol, can you paste the item into a pre-formatted block

```
like this?
```

I think something weird happened with all the tags, making it a little harder to understand the problem.

In your particular example, I'm not sure the merge is needed, although there are certainly examples where a merge of multiple value instances into a single instance would be super-helpful.

What I'd counter-propose would be a MergeFunctionType with a ComponentGroup child and an attribute "@delimiter", which would take a multi-valued component, and mash it together into a single value, with the delimiter placed between each input value.

WDYT?

**Comment by vanderpol** [comment]
Thanks for your feedback David, and I'm game for anything as long as it allows me to process the data in a way that is more useful.   The details of how to do it in OVAL etc... I'm completely opened minded on.   This may exist in other collected items, but this issue exist specifically due to a note in the Windows registry value, which is as follows:

" If the value being tested is of type REG_EXPAND_SZ, then the datatype attribute should be set to 'string' and the pre-expanded string should be represented by the value entity. If the value being tested is of type REG_MULTI_SZ, then only a single string (one of the multiple strings) should be tested using the value entity with the datatype attribute set to 'string'. In order to test multiple values, multiple OVAL registry tests should be used. If the specified registry key is of type REG_SZ, then the datatype should be 'string' and the value entity should be a copy of the string."

Back in May when I was fighting this issue (and then gave up, I was much more in the weeds on the details, so I'm having to dig back and remember it...).  If we can come up with a way to flatten the 1-N 'value' attribute that is created from a Windows reg-multi-size result into a single variable, (with delimiters as you suggested seems wise)

`win-sc:hiveHKEY_LOCAL_MACHINE</win-sc:hive>
  win-sc:keySOFTWARE\Policies\Mozilla\Firefox</win-sc:key>
  win-sc:namePreferences</win-sc:name>
  <win-sc:last_write_time datatype="int">133276820590000000</win-sc:last_write_time>
  win-sc:typereg_multi_sz</win-sc:type>
  win-sc:value{</win-sc:value>
  win-sc:value"security.default_personal_cert": {</win-sc:value>
  win-sc:value"Value": "Ask Every Time",</win-sc:value>
  win-sc:value"Status": "locked"</win-sc:value>
  win-sc:value},</win-sc:value>
  win-sc:value"browser.search.update": {</win-sc:value>
  win-sc:value"Value": false,</win-sc:value>
  win-sc:value"Status": "locked"</win-sc:value>
  win-sc:value},</win-sc:value>
  win-sc:value"dom.disable_window_move_resize": {</win-sc:value>
  win-sc:value"Value": true,</win-sc:value>
  win-sc:value"Status": "locked"</win-sc:value>
  win-sc:value},</win-sc:value>
  win-sc:value"dom.disable_window_flip": {</win-sc:value>
  win-sc:value"Value": true,</win-sc:value>
  win-sc:value"Status": "locked"</win-sc:value>
  win-sc:value},</win-sc:value>
  win-sc:value"browser.contentblocking.category": {</win-sc:value>
  win-sc:value"Value": "strict",</win-sc:value>
  win-sc:value"Status": "locked"</win-sc:value>
  win-sc:value},</win-sc:value>
  win-sc:value"extensions.htmlaboutaddons.recommendations.enabled": {</win-sc:value>
  win-sc:value"Value": false,</win-sc:value>
  win-sc:value"Status": "locked"</win-sc:value>
  win-sc:value}</win-sc:value>
  win-sc:value}</win-sc:value>
  win-sc:windows_view64_bit</win-sc:windows_view>`

Have it available in a variable in a smashed/flattened/merged format that would be great.  This specific example from Firefox already has a comma delimiter built in the reg multi-siz, but lets say we specify a ; as a delimiter, the resulting variable would look like

`"security.default_personal_cert": {;"Value": "Ask Every Time",;"Status": "locked";},;"browser.search.update": {;"Value": false,;"Status": "locked";},;"dom.disable_window_move_resize": {;"Value": true,;"Status": "locked";},;"dom.disable_window_flip": {;"Value": true,;"Status": "locked";},;"browser.contentblocking.category": {;"Value": "strict",;"Status": "locked";},;"extensions.htmlaboutaddons.recommendations.enabled": {;"Value": false,;"Status": "locked";};};`

Having the delimiter be user specified, and optional might be wise as well, as there might be instance where just smashing it all together is exactly what you need.  In this example, a non-delimited output would be:

`"security.default_personal_cert": {"Value": "Ask Every Time","Status": "locked"},"browser.search.update": {"Value": false,"Status": "locked"},"dom.disable_window_move_resize": {"Value": true,"Status": "locked"},"dom.disable_window_flip": {"Value": true,"Status": "locked"},"browser.contentblocking.category": {"Value": "strict","Status": "locked"},"extensions.htmlaboutaddons.recommendations.enabled": {"Value": false,"Status": "locked"}}`

**Comment by vanderpol** [comment]
and that wasn't what I was hoping for... I added the XML as "code" which looks terrible.

**Comment by solind** [comment]
Yes, we could make @delimiter optional (in which case, if excluded, it acts like an empty string), or make it possible to specify an empty string as the attribute value, although I'm not certain whether XML differentiates between an unset attribute and an attribute whose value is an empty string.

I think this is just a slightly more general-purpose function than the convert_to_string function you originally proposed.

Want to update the definitions schema with this and submit a PR to develop?

**Comment by vanderpol** [comment]
@solind would you mind giving this a quick review before I submit a pull request?

    <xsd:complexType name="MergeFunctionType">
        <xsd:annotation>
            <xsd:documentation>The merge function takes two or more components and merges them together into a single string, with an optional delimiter.  For example "abc" and "def would be merged together to form "abcdef" or if using the optional delimiter would be "abc,def"</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence minOccurs="2" maxOccurs="unbounded">
            <xsd:group ref="oval-def:ComponentGroup"/>
        </xsd:sequence>
		<xsd:attribute name="delimiter" type="xsd:string" use="optional" default=""/>
    </xsd:complexType>

**Comment by solind** [comment]
Hi @vanderpol, two comments:
1) You need to close-quote the ```"def``` in the documentation tag
2) It has occurred to me that the order in which the elements are merged is going to end up being arbitrary.  It might be desirable to also have a sort order attribute for the function, with the default being `alphanumeric_ascending` or something like that.  WDYT?

**Comment by vanderpol** [comment]
I'll fix the tag issue... feeling dumb there.

In my primary use case it's from a reg multi-size, and the order that it's
found is key, based on the data being concatenated,  I'll ponder adding an
optional sort order, but not sure yet.

**Comment by vanderpol** [comment]
@solind I'm looking at the other functions (such as concat) which also process data in the same way that this new function will operate, and not seeing any examples of the behavior you are referring to.  Can you point me to an example, or create one?   If you see the pull request, you'll see where it's at right now.  I could merge it into develop and let you take it over as you seem to have a better grasp for what all is needed to make this useful.

**Comment by solind** [comment]
Almost all other functions, such as `concat`, always produce Cartesian products in either case.  This function does not -- the only other function that does something like this is the `count` function, which is documented as follows:

> The count function takes one or more components and returns the count of all of the values represented by the components. For example, assume that two variables exist, each with a single value. By applying the count function against two variable components that resolve to the two variables, the resulting local_variable would have a value of '2'. Additionally, if any of the components referenced by the count function evaluate to a collection of values, then those values are used in the count calculation. For example, assume that there are two components, one of which resolves to a single value, the other of which resolves to two values. If the count function is used to provide a count of these two components, the function will resolve to a local_variable with the values[sic] '3'.

**Comment by vanderpol** [comment]
@solind Sorry to digress here, but in re-reading the OVAL spec for Registry States, I'm wondering of our SCC application is misinterpreting the spec for how to deal with reg_mult_sz, and if so, this entire proposal may not be necessary for my current needs.  Please see the text below in bold, and make sure I'm following it correctly, I feel like in my reading of this, it already matches what I'm looking to do, and we may just need to fix our application.   Thoughts?

The value entity allows a test to be written against the value held within the specified registry key(s). If the value being tested is of type REG_BINARY, then the datatype attribute should be set to 'binary' and the data represented by the value entity should follow the xsd:hexBinary form. (each binary octet is encoded as two hex digits) If the value being tested is of type REG_DWORD, REG_QWORD, REG_DWORD_LITTLE_ENDIAN, REG_DWORD_BIG_ENDIAN, and REG_QWORD_LITTLE_ENDIAN then the datatype attribute should be set to 'int' and the value entity should represent the data as an unsigned integer. DWORD and QWORD values represnt unsigned 32-bit and 64-bit integers, respectively. If the value being tested is of type REG_EXPAND_SZ, then the datatype attribute should be set to 'string' and the pre-expanded string should be represented by the value entity. **If the value being tested is of type REG_MULTI_SZ, then only a single string (one of the multiple strings) should be tested using the value entity with the datatype attribute set to 'string'.** In order to test multiple values, multiple OVAL registry tests should be used. If the specified registry key is of type REG_SZ, then the datatype should be 'string' and the value entity should be a copy of the string. If the value being tested is of type REG_LINK, then the datatype attribute should be set to 'string' and the null-terminated Unicode string should be represented by the value entity.Note that if the intent is to test a version number held in the registry (as a reg_sz) then instead of setting the datatype to 'string', the datatype can be set to 'version'. This allows tools performing the evaluation to know how to perform less than and greater than operations correctly.

**Comment by solind** [comment]
I don't know, that documentation fragment may very well precede the entity_check attribute of EntityStateSimpleBaseType, which more generally governs evaluation in this kind of case.

**Comment by vanderpol** [comment]
In my re-reading of the spec, I'm back to thinking this function is required, and will be updating my branch and submitting a PR later this week.

**Comment by vanderpol** [comment]
I've updated the schema based on your advice @solind and I'm attaching some sample results, as I've implemented it in SCC.  Will be committing the schema shortly and asking for your review.  Attaching as .txt as github doesn't like XML
[SCC-5.10.1_Beta1_2024-10-10_121715_OVAL-Results_registry_merge.xml.txt](https://github.com/user-attachments/files/17331684/SCC-5.10.1_Beta1_2024-10-10_121715_OVAL-Results_registry_merge.xml.txt)

**Comment by solind** [comment]
In your example, I think your variable datatypes should be "string" (not "int") -- using "int" would result in an error in Joval.

I think you should also consider an example that merges an object_component when the object matches multiple system-characteristics items.  For example, an object that collects all the registry values under some particular key.

**Comment by vanderpol** [comment]
See related pull request and merge for more sample results and discussion
