### ISSUE TITLE
Mark OVAL specifications documents as legacy/archive

### ISSUE THREAD

**Issue by vanderpol** [OVAL-Community/OVAL#184]
**Abstract**
Make updates as needed for 5.12, I know that at a minimum we should update it to include the new Merge function added in 5.12, and review in general for other possible updates.

**Link to Proposal**
Once a proposal has been put into pull request form, add a link to the PR here. If and as alternate proposals or objections are added they should be linked here as well.

**Additional context**
Add any other context or screenshots about the enhancement.

**Comment by vanderpol** [comment]
@solind As you appear to have been involved in the creation of the specification files, I'm wondering your opinion as to their worth and if it's worth the time and effort to maintain them going forward.  With all of the changes from 5.11 to 5.12, and with the planned removal of many tests in 6.0, this effort, while noble seems like a lot of time and effort, and most of it redundant to the documentation generate from (and included in) the .xsd files.  Unless someone else on the OVAL board has time to do these justice, I wonder if we should just mark them as archived with 5.11.2?

**Comment by solind** [comment]
@vanderpol That's what I would do (archive and stop producing them).  I don't think anyone requires an old-school specification document anymore.

**Comment by vanderpol** [comment]
I know I've never used them, so that seems like the most cost effective way forward.  Thanks for confirming

**Comment by vanderpol** [comment]
Added readme explaining the files are not being maintained, and to view readthedocs for current documentation.  and renamed directory as archived-oval-specifications.
