### ISSUE TITLE
Update EntityObjectEngineType based on current SQL DBMS engines

### ISSUE THREAD

**Issue by vanderpol** [OVAL-Community/OVAL#185]
**Abstract**
Given the usage of this Type in the sql512 test, we should revisit if this needs update for dbms systems such as MariaDB etc..

**Link to Proposal**
Once a proposal has been put into pull request form, add a link to the PR here. If and as alternate proposals or objections are added they should be linked here as well.

**Additional context**
Add any other context or screenshots about the enhancement.

**Comment by solind** [comment]
Oh yeah, Derby?  I wouldn't be the right person to ask about MariaDB or mySQL specifically.  But my general feeling on engines is, if you need a different or specific driver, and need to write a test for it, that alone would justify adding an entry to the EngineEnumeration.

**Comment by vanderpol** [comment]
I'll do some research online, although I feel like more granularity is better than less, even if there is a possible overlap.  I'll add Derby and MariaDB and do some research on other potentials.

**Comment by vanderpol** [comment]
Apache Derby
MariaDB
MongoDB

Not sure about the following, as they are very similar to SQL Server and PostgreSQL
Azure SQL
Crunchy Data PostgreSQL

**Comment by solind** [comment]
But... Mongo is a no-SQL database!  How would that work?

Also if you're thinking about adding an Azure SQL... what about Amazon Aurora (similar to Postgre and MySQL)?

**Comment by vanderpol** [comment]
Good catch, I missed the fact that Mongo is noSQL... nevermind.  and I'm not sure about all of the cloud based ones, but feel like at worst they won't be used, but really shouldn't hurt to add them.

**Comment by vanderpol** [comment]
Merged pull request, closing issue
