### ISSUE TITLE
can the macos value in the oval:FamilyEnumeration be deprecated in favor of just using the unix value?

### ISSUE THREAD

**Issue by zport** [OVAL-Community/OVAL#60]
@djhaynes commented on [Fri Aug 16 2013](https://github.com/OVAL-Community/Language/issues/71)

In the oval:FamilyEnumeration we have the following values.

-catos
-ios
-macos
-pixos
-undefined
-unix
-vmware_infrastructure
-windows

Under this enumeration, various unix-like platforms are covered under
"unix" including linux variants (RHEL, Debian, etc.), solaris, bsd
variants (FreeBSD, OpenBSD, etc.), and unix variants (HP-UX, IBM AIX, etc.). 
However, you could argue that MacOS is also a unix-like platform.  With that
said, would it make sense to deprecate the "macos" value and just use
the "unix" value instead? Or, is MacOS different enough from the other
unix-like platforms to justify having a separate "macos" value?

---

@solind commented on [Wed Aug 31 2016](https://github.com/OVAL-Community/Language/issues/71#issuecomment-243780629)

There is too much MacOS content that relies on the family to deprecate it now.  (And arguably, there could be a cisco family instead of catos, ios, picos, etc.)

Let's punt on this until 6.0.

**Comment by solind** [comment]
I think we should probably just close this issue. I just don't see a good reason to do it. If anything it would be shared with BSD, but macOS and BSD are so different, it makes no sense for them to share the same family. There will never really be any content common to both platforms.

**Comment by wmunyan** [comment]
Agreed.  I'll close this issue.  If there are any objections, please reopen or create a new issue linked to this one, explaining the rationale for deprecating.
