### ISSUE TITLE
Proposal to add 2 new tests to Linux schema

### ISSUE THREAD

**Issue by wmunyan** [OVAL-Community/OVAL#75]
**Abstract**
A number of current recommendations, specifically in CIS benchmarks, include verifying if linux kernel modules are loaded and/or loadable.  Benchmark recommendations currently utilize unofficial extensions to collect this information.  This proposal means to standardize the collection of both loaded kernel modules and whether or not kernel modules are loadable.

A second proposed construct maps the output of the `sestatus` command to collect and evaluate configurations of SELinux on the endpoint.

**Link to Proposal**
[Updated Pull Request](https://github.com/OVAL-Community/OVAL/pull/88)

**Additional context**
Two new tests are being proposed within the linux schema.  These are the `kernelmodule` test and `sestatus` test.

**Comment by wmunyan** [comment]
Updated test content and results.

[Linux-Kernel-Module-Test-Content-and-Results-v2.zip](https://github.com/OVAL-Community/OVAL/files/2805810/Linux-Kernel-Module-Test-Content-and-Results-v2.zip)

**Comment by solind** [comment]
Do you want to add a content sample for sestatus_test?

**Comment by wmunyan** [comment]
`sestatus` content/results attached.

[linux-def_sestatus_test.zip](https://github.com/OVAL-Community/OVAL/files/3298343/linux-def_sestatus_test.zip)

**Comment by wmunyan** [comment]
PR has been merged; resolving this issue
