### ISSUE TITLE
Schema issue with plist511_test

### ISSUE THREAD

**Issue by dragosprisaca** [OVAL-Community/OVAL#79]
The macos-definitions-schema.xsd schema includes the following mappings:

<oval:element_mapping>
    <oval:test>plist511_test</oval:test>
    <oval:object>plist511_object</oval:object>
    <oval:state>plist511_state</oval:state>
    <oval:item>plist_item</oval:item>
</oval:element_mapping>

This test should use a plist511_item.

Thanks,
_Dragos.

**Comment by zport** [comment]
Issue resolved with PR #80 .
