### ISSUE TITLE
Proposal to add a pwpolicy (5.12) test to Mac OSX schema

### ISSUE THREAD

**Issue by wmunyan** [OVAL-Community/OVAL#84]
**Abstract**
Newer versions of OSX have deprecated the `-getpolicy` option of the `pwpolicy` command in favor of the `-getaccountpolicies` option.  Furthermore, the output of this command takes the form of a plist-like account policy dictionary (XML).

The addition of the `plist512` construct addresses this change, allowing for similar options to the `plist511` construct in terms of allowing for username, authenticator, authenticator password, and directory node values, and adds an `xpath` element to process the resulting XML.

**Link to Proposal**
[Proposal Here](https://github.com/OVAL-Community/OVAL/pull/83)

**Additional context**
Note: Sample content and results still TBD.

**Comment by solind** [comment]
@wmunyan do you know which version of macOS/Darwin added the getaccountpolicies pwpolicy command?

**Comment by solind** [comment]
@wmunyan I'm ready to look at some sample content if you have it.

**Comment by wmunyan** [comment]
@solind i dont have any just yet.  We're in company-wide all-staff meetings this week, so it might not be till next week.  Sorry for the delay.

**Comment by solind** [comment]
Hey Bill... well, now I'm back from my vacation, so if you have that sample content I'm game to get your proposal rolling.

**Comment by wmunyan** [comment]
@solind i realize i'm far behind on this one.  I'll try to prioritize getting some content created; sorry for the delays.

**Comment by solind** [comment]
How about this content?  Does this demonstrate it well enough?

[content.zip](https://github.com/OVAL-Community/OVAL/files/4795923/content.zip)

**Comment by solind** [comment]
https://github.com/OVAL-Community/OVAL/commit/a5ae8d71b311f35cb7f25c5a09dc3bdfdf875a9b
