### ISSUE TITLE
Add new sshd test to Unix schema

### ISSUE THREAD

**Issue by wmunyan** [OVAL-Community/OVAL#87]
**Abstract**
A number of recommendations in CIS benchmarks deal with the configuration of `sshd` service parameters.  This proposal adds the `sshd_(test|object|state|item)` constructs, allowing for the collection and evaluation of these parameter values.

**Link to Proposal**
[Pull Request](https://github.com/OVAL-Community/OVAL/pull/86)

**Additional context**
N/A

**Comment by vanderpol** [comment]
This has already been merged into develop, closing issue
