### ISSUE TITLE
Add HKEY_CURRENT_USER_LOCAL_SETTINGS to EntityStateRegistryHiveType

### ISSUE THREAD

**Issue by dragosprisaca** [OVAL-Community/OVAL#89]
It looks like the EntityStateRegistryHiveType from the  windows-definitions-schema.xsd is missing the value HKEY_CURRENT_USER_LOCAL_SETTINGS. This value was added in the EntityObjectRegistryHiveType (windows-definitions-schema.xsd) and EntityItemRegistryHiveType (windows-system-characteristics-schema.xsd)

Thanks,
_Dragos.

**Comment by solind** [comment]
Another oopsie!  At least you can use a var_ref to work-around this, although that's annoying.

**Comment by wmunyan** [comment]
@dragosprisaca Would you be able to create a pull request, adding that Hive to the `windows-definitions-schema.xsd`?  Reference this ticket, and we can put it through the process.

Cheers, 
-Bill M.

**Comment by vanderpol** [comment]
@dragosprisaca I was going to implement this fix, but in looking at the old MITRE repository, which had the official 5.11.2 release, I see HKEY_CURRENT_USER_LOCAL_SETTINGS in the EntityObjectRegistryHiveType, I also see the same for the windows def schema file in the master on this repository, which hasn't been updated really ever.  Can you confirm that this is still an issue?

Here's the official 5.11.2 from MITRE:  
https://github.com/OVALProject/Language/blob/master/schemas/windows-definitions-schema.xsd

Here's our current 'master' on the OVAL-Community repo:
https://github.com/OVAL-Community/OVAL/blob/master/oval-schemas/windows-definitions-schema.xsd

**Comment by solind** [comment]
It’s still an issue in the develop branch (and also in stable) — it’s enumerated in the EntityObjectRegistryHiveType, but there needs to be a corresponding enumeration entry in the EntityStateRegistryHiveType.

**Comment by vanderpol** [comment]
Thanks David, I realized my mistake after posting my comment and deleted
it... I think it's now fixed, just need to do a pull request on my fix.

**Comment by vanderpol** [comment]
Merged pull request, closing issue
