### ISSUE TITLE
ind-def:textfilecontent54_object/instance documentation issue for value = 0

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#92]
**Describe the bug**
Remember https://github.com/OVALProject/Language/issues/277?

Well, the schema documentation discusses positive and negative numbers in the context of the ind-def:textfilecontent54_object/instance entity -- but we don't talk about what to do if the value is set to 0.

**Replication Steps** (if applicable)
N/A

**Expected behavior**
We should probably clarify that we actually mean negative integers, and non-negative integers (instead of positive integers).

**Content**
I've seen CIS compliance content designed to look for instance "greater than" to 0.  These can be safely changed to "greater than or equal" to 1, but that's just a work-around to avoid the ambiguity of the standard.

**OVAL details** (complete all those relevant)
 - Schema: ind-def/ind-sc
 - Test: textfilecontent54_test
 - Object: textfilecontent54_object
 - State: textfilecontent54_state
 - Item: textfilecontent54_item

**Additional context**
More of an "oh by the way" -- the schema documentation also refers to the operation enumeration value "greater than or equal" as "greater than or equals[sic]", which is incorrect.  We should fix that, too.

**Comment by wmunyan** [comment]
Closing this issue as it's already been merged into the "development" branch.
