### ISSUE TITLE
Proposals for querying macos install history data

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#95]
**Abstract**
There is not currently any way to inspect the install history of a macOS device using OVAL.  Normally this information can be queried using the command:

```
system_profiler SPInstallHistoryDataType
```

However, even the macos:systemprofiler_[object/state/item]'s Entity[Object/State/Item]DataTypeType lacks an enumerated value for the install history.

**Link to Proposal**
PR is forthcoming.  However, the proposal consists of two parts:

Part 1: Update the DataTypeType enumeration to include new values available to the system_profiler command.

Part 2: Create a new test oriented around the install history data to make it simple to query, as the XPaths that would be required to retrieve the information using the system_profiler test will be very complex, and besides, would not be usable to associate like data together (i.e., a software title and its install date).

**Additional context**
Add any other context or screenshots about the enhancement.

See the Joval open-source data model project's unofficial OVAL schema elements here:
https://github.com/joval/jOVAL/tree/master/scap/schemas/oval/unofficial

Specifically, the files:
macos-datatypetype-def-schema.xsd
macos-datatypetype-sc-schema.xsd
macos-installhistory-def-schema.xsd
macos-installhistory-sc-schema.xsd

**Comment by wmunyan** [comment]
no objections to this proposal.

one nit - the "abstract" section above shows the `system_profiler` command with a `-` in front of the `SPInstallHistoryDataType`.  The command doesnt have the `-`, and its not in the schemas (correctly).  Like I say...just a nit in the abstract.

**Comment by solind** [comment]
@wmunyan Ha!  Fixed it, thanks!

**Comment by solind** [comment]
https://github.com/OVAL-Community/OVAL/commit/a5ae8d71b311f35cb7f25c5a09dc3bdfdf875a9b
