### ISSUE TITLE
Improve OVAL Leadership Board-related process documentation

### ISSUE THREAD

**Issue by DavidRies** [OVAL-Community/OVAL#97]
The current [OVAL Leadership Board process documentation](https://oval-community-guidelines.readthedocs.io/en/latest/community-organization/oval-leadership-board.html) is not complete. Not all of the processes were migrated from the legacy MITRE pages (see [here](https://oval.mitre.org/community/board/voting.html#who) and [here](https://oval.mitre.org/community/board/processes.html)).

The current [OVAL Leadership Board process documentation](https://oval-community-guidelines.readthedocs.io/en/latest/community-organization/oval-leadership-board.html) covers:
 - description of the role
 - listing of various the members 
 - documentation of responsibilities
 - the appointment process

However, we failed to migrate over several details from the MITRE pages, for example:
- who may vote
- announcing a vote
- quorum
- role changes
- etc.

I suggest we migrate the relevant/missing MITRE documentation over to our current site for clarity and completeness, without changing any of the missing rules/processes themselves.

In the absence of feedback to the contrary, I will follow the current proposal process and create a PR to effect this.

**Comment by adammontville** [comment]
Thanks for bringing posting this issue and taking the ball, David. No objection to migrating the relevant/missing MITRE documentation to our current site.
