### ISSUE TITLE
Add GeneratedUID to macos:accountinfo_item

### ISSUE THREAD

**Issue by solind** [OVAL-Community/OVAL#99]
**Abstract**
The GeneratedUID is a field associated with macOS user accounts that's related to the T2 chip and FileVault.  OVAL currently lacks a mechanism to retrieve it.  We could easily just add it to the accountinfo_item/state.

**Link to Proposal**
PR to come

**Additional context**
See attachment for sample result XML

[content.zip](https://github.com/OVAL-Community/OVAL/files/4795968/content.zip)

**Comment by wmunyan** [comment]
No objections.

**Comment by solind** [comment]
https://github.com/OVAL-Community/OVAL/commit/a5ae8d71b311f35cb7f25c5a09dc3bdfdf875a9b
